name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace placeholder values
        uses: microsoft/replace-action@v2
        with:
          file: .env  # Specify the file where the placeholder is located
          placeholder: 'MEANING_OF_LIFE_PLACEHOLDER'  # The placeholder in your file
          value: ${{ secrets.MEANING_OF_LIFE }}  # This is your secret

      - name: Deploy application
        run: |
          # Add your deployment commands here, e.g.,
          npm install
          npm run build
          npm run deploy
